# Generated by Django 4.2.1 on 2023-05-17 08:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="User's names")),
                ('last_name', models.CharField(max_length=50, verbose_name="User's last names")),
                ('patronymic', models.CharField(max_length=50, verbose_name="User's patronymic")),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('\\d{11}', 'Minimum 11', code='invalid')], verbose_name="User's phone")),
            ],
        ),
    ]
